[build-system]
requires = ["scikit-build-core>=0.5", "pybind11>=2.12"]
build-backend = "scikit_build_core.build"

[project]
name = "parshred"
version = "0.1.0"
description = "The World's Fastest XML Parser"
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"

[tool.scikit-build]
cmake.args = ["-DPARSHRED_BUILD_PYTHON=ON", "-DPARSHRED_BUILD_TESTS=OFF", "-DPARSHRED_BUILD_BENCH=OFF", "-DPARSHRED_BUILD_CLI=OFF"]
